gradleVersion = 8.2

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890

org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
kotlin.incremental=true
kotlin.stdlib.default.dependency=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=false

kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
kotlin.compiler.classNotFoundErrorForWarning=false

org.gradle.java.installations.auto-detect=true

